# Site settings
title: Nikos Roumeliotis
description: This is my profile
baseurl: "/"
url: "https://nikos.rocks"

# User settings
username: Nikos Roumeliotis
user_description: This is my profile
user_title: Eth. Hacker | PenTester | AppSec
email: nikos.roume@outlook.com
twitter_username: '#'
github_username:  '#'
gplus_username:  '#'

# Google-analytics
google-analytics:
  id: "UA-213690118-1"

exclude: ['package.json', 'src' , 'node_modules']
